class FutuException(Exception):
    def __init__(self, message="FutuError"):
        super().__init__(message)
        pass
